kind: Service
apiVersion: v1
metadata:
  name: nextjs-service
spec:
  type: LoadBalancer
  selector:
    app: nextjs-app
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000